import { initializeApp } from "firebase/app";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { getFirestore, doc, writeBatch } from "firebase/firestore";
import fs from 'fs';
import dotenv from 'dotenv';

dotenv.config();

const firebaseConfig = {
  apiKey: "AIzaSyA3-2GbzNSBHv__hfaJzvqIdgV_ozvVgfE",
  authDomain: "interlix-2d61f.firebaseapp.com",
  projectId: "interlix-2d61f",
  storageBucket: "interlix-2d61f.firebasestorage.app",
  messagingSenderId: "106645468469",
  appId: "1:106645468469:web:e4ffc62c4d7eb6e9a8087c",
  measurementId: "G-KPY7Z9GJEX"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

async function remapAndInject() {
  try {
    let rawDataString = fs.readFileSync('demo_data.json', 'utf8');
    const rawData = JSON.parse(rawDataString);
    
    const oldUidToCreds = new Map();

    // 1. Find all old UIDs and their credentials
    if (rawData.userData) {
      for (const userId in rawData.userData) {
        const collections = rawData.userData[userId];
        if (collections.employees) {
          for (const emp of collections.employees) {
            // we assume the employee document ID or `userId` field is the old UID
            if (emp.email && emp.password) {
              oldUidToCreds.set(emp.userId || emp.id, { email: emp.email, password: emp.password });
            }
          }
        }
      }
    }

    console.log(`Found ${oldUidToCreds.size} employee accounts to remap.`);

    // 2. Sign in to each account to get the NEW UID generated by Firebase Auth
    for (const [oldUid, creds] of oldUidToCreds.entries()) {
      try {
        const userCredential = await signInWithEmailAndPassword(auth, creds.email, creds.password);
        const newUid = userCredential.user.uid;
        
        console.log(`Mapped ${creds.email}: ${oldUid} -> ${newUid}`);
        
        // Globally replace the old UID with the new UID in the JSON string
        rawDataString = rawDataString.split(oldUid).join(newUid);
      } catch (error) {
        console.error(`Failed to sign in ${creds.email}:`, error.message);
      }
    }

    // 3. Write remapped data for debugging
    fs.writeFileSync('demo_data_remapped.json', rawDataString);
    const remappedData = JSON.parse(rawDataString);
    
    // 4. Inject remapped data into Firestore
    const ops = [];

    if (remappedData.roles) {
      for (const role of remappedData.roles) {
        const id = role.id;
        delete role.id;
        ops.push({ ref: doc(db, 'users', id), data: role });
      }
    }

    if (remappedData.userData) {
      for (const userId in remappedData.userData) {
        const collections = remappedData.userData[userId];
        for (const subName in collections) {
          const docs = collections[subName];
          for (const d of docs) {
            const id = d.id;
            delete d.id;
            ops.push({ ref: doc(db, `userData/${userId}/${subName}`, id), data: d });
          }
        }
      }
    }

    console.log(`Found ${ops.length} documents to inject. Executing in batches...`);
    
    let operations = 0;
    for (let i = 0; i < ops.length; i += 500) {
      const batch = writeBatch(db);
      const chunk = ops.slice(i, i + 500);
      for (const op of chunk) {
        batch.set(op.ref, op.data);
      }
      await batch.commit();
      operations += chunk.length;
      console.log(`Injected ${operations}/${ops.length} documents...`);
    }

    console.log(`Successfully injected ${operations} remapped documents into Firestore.`);
    process.exit(0);
  } catch (error) {
    console.error("Script failed:", error);
    process.exit(1);
  }
}

remapAndInject();
